services:
  docscan-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: always
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
    ports:
      - "5173:5173"
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host" ]

  vite-react-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
