services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy

    command: fastapi dev main.py --host 0.0.0.0 --port 8000
    restart: always
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
        - action: rebuild
          path: requirements.txt

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 5

volumes:
  postgres_data:

      
